# Generated by Django 4.2.9 on 2024-02-19 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=255)),
                ('url', models.CharField(default='https://graph.facebook.com/', editable=False, max_length=255)),
                ('version', models.CharField(default='v18.0', editable=False, max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=90)),
                ('user', models.ManyToManyField(to='website.record')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Communication_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_message_text', models.TextField()),
                ('group_sent_datetime', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.group_record')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sender')),
            ],
        ),
        migrations.CreateModel(
            name='Communication_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('message_text', models.TextField()),
                ('sent_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sender')),
            ],
        ),
    ]
