# Generated by Django 5.0.1 on 2024-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_communication_record',
            name='group_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
