# Generated by Django 5.0.1 on 2024-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication_record',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
