# Generated by Django 5.0.1 on 2024-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_group_communication_record_group_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_communication_record',
            name='group_status',
            field=models.CharField(default='unknown', max_length=400),
        ),
    ]
