# Generated by Django 5.0.1 on 2024-02-25 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_communication_record_send_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_record',
            name='group_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
